export default {
  'import-x/no-unresolved': [
    'error',
    {
      commonjs: true,
      caseSensitive: true,
    },
  ],
  'import-x/named': 'error',
  'import-x/default': 'off',
  'import-x/namespace': 'off',
  'import-x/export': 'error',
  'import-x/no-named-as-default': 'off',
  'import-x/no-named-as-default-member': 'error',
  'import-x/no-deprecated': 'off',
  'import-x/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: true,
    },
  ],
  'import-x/no-mutable-exports': 'error',
  'import-x/no-commonjs': 'off',
  'import-x/no-amd': 'error',
  'import-x/no-nodejs-modules': 'off',
  'import-x/first': 'error',
  'import-x/no-duplicates': 'error',
  'import-x/no-namespace': 'off',
  'import-x/extensions': [
    'warn',
    'ignorePackages',
    {
      js: 'always',
      jsx: 'never',
      ts: 'never',
      tsx: 'never',
      json: 'always',
      css: 'always',
      scss: 'always',
    },
  ],
  'import-x/order': 'off',
  'import-x/newline-after-import': 'error',
  'import-x/prefer-default-export': 'off',
  'import-x/no-restricted-paths': 'off',
  'import-x/max-dependencies': 'off',
  'import-x/no-absolute-path': 'error',
  'import-x/no-dynamic-require': 'error',
  'import-x/no-internal-modules': 'off',
  'import-x/unambiguous': 'off',
  'import-x/no-webpack-loader-syntax': 'error',
  'import-x/no-unassigned-import': 'off',
  'import-x/no-named-default': 'error',
  'import-x/no-anonymous-default-export': 'off',
  'import-x/exports-last': 'off',
  'import-x/group-exports': 'off',
  'import-x/no-default-export': 'off',
  'import-x/no-self-import': 'error',
  'import-x/no-cycle': 'error',
  'import-x/no-useless-path-segments': [
    'error',
    {
      commonjs: true,
    },
  ],
  'import-x/dynamic-import-chunkname': 'off',
  'import-x/no-relative-parent-imports': 'off',
  'import-x/no-unused-modules': 'off',
  'import-x/no-import-module-exports': 'off',
  'import-x/no-relative-packages': 'error',
};
