module.exports = {
  'import/no-unresolved': [
    'error',
    {
      commonjs: true,
      caseSensitive: true,
    },
  ],
  'import/named': 'error',
  'import/default': 'off',
  'import/namespace': 'off',
  'import/export': 'error',
  'import/no-named-as-default': 'off',
  'import/no-named-as-default-member': 'error',
  'import/no-deprecated': 'off',
  'import/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: true,
    },
  ],
  'import/no-mutable-exports': 'error',
  'import/no-commonjs': 'off',
  'import/no-amd': 'error',
  'import/no-nodejs-modules': 'off',
  'import/first': 'error',
  'import/imports-first': 'off',
  'import/no-duplicates': 'error',
  'import/no-namespace': 'off',
  'import/extensions': [
    'warn',
    'never',
    {
      json: 'always',
      css: 'always',
      scss: 'always',
    },
  ],
  'import/order': 'off',
  'import/newline-after-import': 'error',
  'import/prefer-default-export': 'off',
  'import/no-restricted-paths': 'off',
  'import/max-dependencies': 'off',
  'import/no-absolute-path': 'error',
  'import/no-dynamic-require': 'error',
  'import/no-internal-modules': 'off',
  'import/unambiguous': 'off',
  'import/no-webpack-loader-syntax': 'error',
  'import/no-unassigned-import': 'off',
  'import/no-named-default': 'error',
  'import/no-anonymous-default-export': 'off',
  'import/exports-last': 'off',
  'import/group-exports': 'off',
  'import/no-default-export': 'off',
  'import/no-self-import': 'error',
  'import/no-cycle': 'error',
  'import/no-useless-path-segments': [
    'error',
    {
      commonjs: true,
    },
  ],
  'import/dynamic-import-chunkname': 'off',
  'import/no-relative-parent-imports': 'off',
  'import/no-unused-modules': 'off',
  'import/no-import-module-exports': 'off',
  'import/no-relative-packages': 'error',
};
