export default {
  'n/callback-return': 'off',
  'n/exports-style': ['warn', 'module.exports'],
  'n/file-extension-in-import': 'off',
  'n/global-require': 'warn',
  'n/handle-callback-err': 'warn',
  'n/hashbang': 'error',
  'n/no-callback-literal': 'warn',
  'n/no-deprecated-api': 'error',
  'n/no-exports-assign': 'error',
  'n/no-extraneous-import': 'off',
  'n/no-extraneous-require': 'off',
  'n/no-missing-import': 'off',
  'n/no-missing-require': 'off',
  'n/no-mixed-requires': 'warn',
  'n/no-new-require': 'error',
  'n/no-path-concat': 'error',
  'n/no-process-env': 'off',
  'n/no-process-exit': 'warn',
  'n/no-restricted-import': 'off',
  'n/no-restricted-require': 'off',
  'n/no-sync': 'off',
  'n/no-unpublished-bin': 'error',
  'n/no-unpublished-import': 'off',
  'n/no-unpublished-require': 'off',
  'n/no-unsupported-features/es-builtins': 'off',
  'n/no-unsupported-features/es-syntax': 'off',
  'n/no-unsupported-features/node-builtins': 'off',
  'n/prefer-global/buffer': ['warn', 'always'],
  'n/prefer-global/console': ['warn', 'always'],
  'n/prefer-global/process': ['warn', 'always'],
  'n/prefer-global/text-decoder': ['warn', 'always'],
  'n/prefer-global/text-encoder': ['warn', 'always'],
  'n/prefer-global/url': ['warn', 'always'],
  'n/prefer-global/url-search-params': ['warn', 'always'],
  'n/prefer-node-protocol': 'warn',
  'n/prefer-promises/dns': 'warn',
  'n/prefer-promises/fs': 'warn',
  'n/process-exit-as-throw': 'error',
};
