export default {
  'react/boolean-prop-naming': 'off',
  'react/button-has-type': [
    'error',
    {
      button: true,
      submit: true,
      reset: false,
    },
  ],
  'react/destructuring-assignment': ['error', 'always'],
  'react/display-name': 'off',
  'react/forbid-component-props': 'off',
  'react/forbid-dom-props': 'off',
  'react/forbid-elements': 'off',
  'react/function-component-definition': [
    'error',
    {
      namedComponents: 'function-declaration',
    },
  ],
  'react/hook-use-state': 'off',
  'react/iframe-missing-sandbox': 'error',
  'react/no-adjacent-inline-elements': 'off',
  'react/no-array-index-key': 'warn',
  'react/no-children-prop': 'error',
  'react/no-danger': 'warn',
  'react/no-danger-with-children': 'error',
  'react/no-deprecated': ['error'],
  'react/no-find-dom-node': 'error',
  'react/no-invalid-html-attribute': 'error',
  'react/no-multi-comp': 'off',
  'react/no-namespace': 'error',
  'react/no-object-type-as-default-prop': 'error',
  'react/no-render-return-value': 'error',
  'react/no-this-in-sfc': 'error',
  'react/no-unescaped-entities': 'off',
  'react/no-unknown-property': 'error',
  'react/no-unsafe': 'off',
  'react/no-unstable-nested-components': ['error', { allowAsProps: true }],
  'react/prefer-read-only-props': 'off',
  'react/react-in-jsx-scope': 'off',
  'react/require-optimization': 'off',
  'react/self-closing-comp': 'error',
  'react/style-prop-object': 'error',
  'react/void-dom-elements-no-children': 'error',
  'react/jsx-boolean-value': [
    'error',
    'never',
    {
      always: [],
    },
  ],
  'react/jsx-child-element-spacing': 'off',
  'react/jsx-filename-extension': 'off',
  'react/jsx-handler-names': 'off',
  'react/jsx-key': 'off',
  'react/jsx-max-depth': 'off',
  'react/jsx-newline': 'off',
  'react/jsx-no-bind': [
    'error',
    {
      ignoreRefs: true,
      allowArrowFunctions: true,
      allowFunctions: false,
      allowBind: false,
      ignoreDOMComponents: true,
    },
  ],
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-no-constructed-context-values': 'error',
  'react/jsx-no-duplicate-props': [
    'error',
    {
      ignoreCase: true,
    },
  ],
  'react/jsx-no-leaked-render': 'off',
  'react/jsx-no-literals': 'off',
  'react/jsx-no-script-url': [
    'error',
    [
      {
        name: 'Link',
        props: ['to'],
      },
    ],
  ],
  'react/jsx-no-target-blank': [
    'error',
    {
      enforceDynamicLinks: 'always',
    },
  ],
  'react/jsx-no-undef': 'error',
  'react/jsx-no-useless-fragment': 'error',
  'react/jsx-curly-brace-presence': [
    'error',
    {
      props: 'never',
      children: 'never',
    },
  ],
  'react/jsx-pascal-case': [
    'error',
    {
      allowAllCaps: true,
      ignore: [],
    },
  ],
  'react/jsx-props-no-spreading': 'off',
  'react/jsx-sort-props': [
    'warn',
    {
      reservedFirst: true,
    },
  ],
  'react/jsx-fragments': 'off',
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 'warn',
};
